test results in build step

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -12,25 +12,6 @@ commands:
       - run: sudo apt update
       - run: sudo apt install libxml-xpath-perl
 
-  build-test-results:
-    parameters:
-      service:
-        type: string
-
-    steps:
-      - buildevents/add_context:
-          field_name: ci.tests.build.completed
-          field_value: $(xpath -q -e 'failsafe-summary/completed/text()'  << parameters.service >>/target/failsafe-reports/failsafe-summary.xml)
-      - buildevents/add_context:
-          field_name: ci.tests.build.errors
-          field_value: $(xpath -q -e 'failsafe-summary/errors/text()'  << parameters.service >>/target/failsafe-reports/failsafe-summary.xml)
-      - buildevents/add_context:
-          field_name: ci.tests.build.failures
-          field_value: $(xpath -q -e 'failsafe-summary/failures/text()'  << parameters.service >>/target/failsafe-reports/failsafe-summary.xml)
-      - buildevents/add_context:
-          field_name: ci.tests.build.skipped
-          field_value: $(xpath -q -e 'failsafe-summary/skipped/text()'  << parameters.service >>/target/failsafe-reports/failsafe-summary.xml)
-
 jobs:
 
   setup:
@@ -65,14 +46,18 @@ jobs:
 
             - buildevents/berun:
                 bename: Build-welcome-member-email-service
-                becommand: mvn clean verify -pl credit-score-service -Pcode-coverage -Pstatic-code-analysis
+                becommand: |
+                  exit_code=$(mvn clean verify -pl credit-score-service -Pcode-coverage -Pstatic-code-analysis 2>&1)
 
-            - when:
-                condition:
-                  bool: on_success || on_failure
-                steps:
-                  - build-test-results:
-                      service: welcome-member-email-service
+                  cat $BUILDEVENT_FILE > ./step_specific_buildevents_file.txt
+                  BUILDEVENT_FILE=./step_specific_buildevents_file.txt
+                  echo " ci.tests.build.completed=$(xpath -q -e 'failsafe-summary/completed/text()'  welcome-member-email-service/target/failsafe-reports/failsafe-summary.xml)" >> $BUILDEVENT_FILE
+                  echo " ci.tests.build.errors=$(xpath -q -e 'failsafe-summary/errors/text()'  welcome-member-email-service/target/failsafe-reports/failsafe-summary.xml)" >> $BUILDEVENT_FILE
+                  echo " ci.tests.build.failures=$(xpath -q -e 'failsafe-summary/failures/text()'  welcome-member-email-service/target/failsafe-reports/failsafe-summary.xml)" >> $BUILDEVENT_FILE
+                  echo " ci.tests.build.skipped=$(xpath -q -e 'failsafe-summary/skipped/text()'  welcome-member-email-service/target/failsafe-reports/failsafe-summary.xml)" >> $BUILDEVENT_FILE
+                  rm ./step_specific_buildevents_file.txt
+
+                  exit $exit_code
 
             - buildevents/berun:
                 bename: Pact-build-and-test-welcome-member-email-service
@@ -92,14 +77,18 @@ jobs:
 
             - buildevents/berun:
                 bename: Build-special-membership-service
-                becommand: mvn clean verify -pl special-membership-service -Pcode-coverage -Pstatic-code-analysis
+                becommand: |
+                  exit_code=$(mvn clean verify -pl special-membership-service -Pcode-coverage -Pstatic-code-analysis2>&1)
 
-            - when:
-                condition:
-                  bool: on_success || on_failure
-                steps:
-                  - build-test-results:
-                      service: special-membership-service
+                  cat $BUILDEVENT_FILE > ./step_specific_buildevents_file.txt
+                  BUILDEVENT_FILE=./step_specific_buildevents_file.txt
+                  echo " ci.tests.build.completed=$(xpath -q -e 'failsafe-summary/completed/text()'  special-membership-service/target/failsafe-reports/failsafe-summary.xml)" >> $BUILDEVENT_FILE
+                  echo " ci.tests.build.errors=$(xpath -q -e 'failsafe-summary/errors/text()'  special-membership-service/target/failsafe-reports/failsafe-summary.xml)" >> $BUILDEVENT_FILE
+                  echo " ci.tests.build.failures=$(xpath -q -e 'failsafe-summary/failures/text()'  special-membership-service/target/failsafe-reports/failsafe-summary.xml)" >> $BUILDEVENT_FILE
+                  echo " ci.tests.build.skipped=$(xpath -q -e 'failsafe-summary/skipped/text()'  special-membership-service/target/failsafe-reports/failsafe-summary.xml)" >> $BUILDEVENT_FILE
+                  rm ./step_specific_buildevents_file.txt
+
+                  exit $exit_code
 
             - buildevents/berun:
                 bename: Pact-build-and-test-special-membership-service
@@ -121,14 +110,18 @@ jobs:
 
             - buildevents/berun:
                 bename: Build-credit-score-service
-                becommand: mvn clean verify -pl credit-score-service -Pcode-coverage -Pstatic-code-analysis
+                becommand: |
+                  exit_code=$(mvn clean verify -pl credit-score-service -Pcode-coverage -Pstatic-code-analysis2>&1)
 
-            - when:
-                condition:
-                  bool: on_success || on_failure
-                steps:
-                  - build-test-results:
-                      service: credit-score-service
+                  cat $BUILDEVENT_FILE > ./step_specific_buildevents_file.txt
+                  BUILDEVENT_FILE=./step_specific_buildevents_file.txt
+                  echo " ci.tests.build.completed=$(xpath -q -e 'failsafe-summary/completed/text()'  credit-score-service/target/failsafe-reports/failsafe-summary.xml)" >> $BUILDEVENT_FILE
+                  echo " ci.tests.build.errors=$(xpath -q -e 'failsafe-summary/errors/text()'  credit-score-service/target/failsafe-reports/failsafe-summary.xml)" >> $BUILDEVENT_FILE
+                  echo " ci.tests.build.failures=$(xpath -q -e 'failsafe-summary/failures/text()'  credit-score-service/target/failsafe-reports/failsafe-summary.xml)" >> $BUILDEVENT_FILE
+                  echo " ci.tests.build.skipped=$(xpath -q -e 'failsafe-summary/skipped/text()'  credit-score-service/target/failsafe-reports/failsafe-summary.xml)" >> $BUILDEVENT_FILE
+                  rm ./step_specific_buildevents_file.txt
+
+                  exit $exit_code
 
             - buildevents/berun:
                 bename: Pact-build-and-test-credit-score-service
